import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { CircleHelp, Command, Settings2, SlidersHorizontal, ArrowRight, Clock3, UploadCloud, UsersRound, MapPin } from 'lucide-react';
import SoccerField from './components/SoccerField';
import PlaybackControls from './components/PlaybackControls';
import Timeline from './components/Timeline';
import ClipCreator from './components/ClipCreator';
import ClipLibrary from './components/ClipLibrary';
import PlayerInfo from './components/PlayerInfo';
import MatchLoadingOverlay from './components/MatchLoadingOverlay';
import PixelCharacters from './components/PixelCharacters';
import PitchAnnotationTools from './components/PitchAnnotationTools';
import SuggestedMoments from './components/SuggestedMoments';
import { MatchLoader, MatchSelector } from './components/MatchSelector';
import { discoverMatches, fallbackMatches, loadLocalFile, loadMatch } from './services/matchLoader';
import type { MatchOption, PitchAnnotation, SavedClip, TrackingFrame, TrackingPlayer } from './types/tracking';
import { formatTime } from './utils/timeFormatting';
import { suggestMoments } from './utils/suggestMoments';
import './styles.css';

export default function App() {
  const [matches,setMatches]=useState(fallbackMatches), [selectedMatch,setSelectedMatch]=useState(fallbackMatches[0].id), [match,setMatch]=useState<MatchOption|null>(null), [frames,setFrames]=useState<TrackingFrame[]>([]), [loading,setLoading]=useState(false), [error,setError]=useState<string|null>(null);
  const [time,setTime]=useState(0), [playing,setPlaying]=useState(false), [speed,setSpeed]=useState(1), [selectedPlayer,setSelectedPlayer]=useState<string|null>(null), [clipStart,setClipStart]=useState<number|null>(null), [clipEnd,setClipEnd]=useState<number|null>(null), [title,setTitle]=useState(''), [notes,setNotes]=useState(''), [tags,setTags]=useState(''), [clips,setClips]=useState<SavedClip[]>([]), [annotations,setAnnotations]=useState<PitchAnnotation[]>([]), [drawMode,setDrawMode]=useState<PitchAnnotation['kind']|null>(null), [trails,setTrails]=useState(false), [labels,setLabels]=useState(false), [speedLabels,setSpeedLabels]=useState(false), [ballTrail,setBallTrail]=useState(false), [shape,setShape]=useState(false), [toast,setToast]=useState('');
  const clipStop=useRef<number|null>(null), timeRef=useRef(time), initialUrl=useRef(new URL(location.href)), initialRouteHandled=useRef(false), localFrames=useRef(new Map<string,TrackingFrame[]>()); timeRef.current=time;
  const duration=match?.duration ?? 5400;
  const currentFrame=useMemo(()=>{if(!frames.length)return null;let lo=0,hi=frames.length-1;while(lo<hi){const mid=(lo+hi+1)>>1;if(frames[mid].timestamp<=time)lo=mid;else hi=mid-1;}const before=frames[lo],after=frames[Math.min(lo+1,frames.length-1)],span=after.timestamp-before.timestamp,t=span>0?Math.max(0,Math.min(1,(time-before.timestamp)/span)):0;if(t===0||before===after)return before;const lerp=(a:number|undefined,b:number|undefined)=>a===undefined?b??0:b===undefined?a:a+(b-a)*t;return{...before,timestamp:time,players:before.players.map(player=>{const next=after.players.find(p=>p.id===player.id);return next?{...player,x:lerp(player.x,next.x),y:lerp(player.y,next.y),speed:lerp(player.speed,next.speed),distance:lerp(player.distance,next.distance)}:player;}),ball:{x:lerp(before.ball.x,after.ball.x),y:lerp(before.ball.y,after.ball.y)}};},[frames,time]);
  const activePlayer:TrackingPlayer|null=currentFrame?.players.find(p=>p.id===selectedPlayer)??null;
  const suggestions=useMemo(()=>suggestMoments(frames),[frames]);
  const doLoad=useCallback(async (opt?:MatchOption)=>{const chosen=opt??matches.find(m=>m.id===selectedMatch);if(!chosen)return;setLoading(true);setError(null);setPlaying(false);try{const cached=chosen.source==='local'?localFrames.current.get(chosen.id):undefined;const result=cached?{match:chosen,frames:cached}:await loadMatch(chosen),data=result.frames;if(!data.length)throw new Error('No tracking frames are available for this match.');setSelectedMatch(chosen.id);setMatch(result.match);setFrames(data);setClips([]);setAnnotations([]);const sharedStart=Number(initialUrl.current.searchParams.get('start')),sharedEnd=Number(initialUrl.current.searchParams.get('end'));const hasShared=initialUrl.current.pathname.endsWith(encodeURIComponent(chosen.id))&&Number.isFinite(sharedStart)&&Number.isFinite(sharedEnd)&&sharedEnd>sharedStart;if(hasShared){setTime(sharedStart);setClipStart(sharedStart);setClipEnd(sharedEnd);clipStop.current=sharedEnd;}else{setTime(data[0]?.timestamp??0);setClipStart(null);setClipEnd(null);clipStop.current=null;}setSelectedPlayer(null);const path=hasShared?`${initialUrl.current.pathname}${initialUrl.current.search}`:`/match/${encodeURIComponent(chosen.id)}`;window.history.replaceState({},'',path);initialUrl.current=new URL(window.location.href);}catch(e){setError(e instanceof Error?e.message:'Unable to load match.');}finally{setLoading(false);}},[matches,selectedMatch]);
  const doFile=async(file:File)=>{setLoading(true);setError(null);try{const result=await loadLocalFile(file);localFrames.current.set(result.match.id,result.frames);setMatches(existing=>[result.match,...existing.filter(m=>m.id!==result.match.id)]);setMatch(result.match);setFrames(result.frames);setClips([]);setAnnotations([]);setTime(result.frames[0].timestamp);setPlaying(false);setSelectedPlayer(null);setSelectedMatch(result.match.id);window.history.replaceState({},'',`/match/${encodeURIComponent(result.match.id)}`);initialUrl.current=new URL(window.location.href);}catch(e){setError(e instanceof Error?e.message:'Could not parse tracking file.');}finally{setLoading(false);}};
  useEffect(()=>{void discoverMatches().then(found=>{setMatches(found);const path=initialUrl.current.pathname;if(path==='/'||path==='/index.html'){const firstReal=found.find(m=>m.source==='skillcorner');if(firstReal)setSelectedMatch(firstReal.id);}});},[]);
  useEffect(()=>{if(initialRouteHandled.current)return;const pathId=initialUrl.current.pathname.split('/').filter(Boolean).at(-1);const routeMatch=matches.find(m=>m.id===pathId);if(routeMatch){initialRouteHandled.current=true;setSelectedMatch(routeMatch.id);void doLoad(routeMatch);}else if(!pathId||pathId==='index.html'){initialRouteHandled.current=true;}},[matches,doLoad]);
  useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>{const next=timeRef.current+0.1*speed;if(clipStop.current!==null&&next>=clipStop.current){setTime(clipStop.current);timeRef.current=clipStop.current;setPlaying(false);clipStop.current=null;}else if(next>=duration){setTime(duration);setPlaying(false);}else setTime(next);},100);return()=>window.clearInterval(id);},[playing,speed,duration]);
  useEffect(()=>{if(!toast)return;const id=window.setTimeout(()=>setToast(''),2400);return()=>window.clearTimeout(id);},[toast]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;if(target&&(target.tagName==='INPUT'||target.tagName==='TEXTAREA'||target.tagName==='SELECT'||target.isContentEditable))return;if(event.code==='Space'){event.preventDefault();setPlaying(v=>!v);}if(event.code==='ArrowLeft')setTime(v=>Math.max(0,v-10));if(event.code==='ArrowRight')setTime(v=>Math.min(duration,v+10));};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[duration]);
  const playClip=(clip:SavedClip)=>{setTime(clip.start);setAnnotations(clip.annotations??[]);clipStop.current=clip.end;setPlaying(true);};
  const shareClip=async(clip:SavedClip)=>{if(match?.source==='local'){setToast('This clip uses a local file. Shareable links need the same match in the prepared data folder.');return;}const url=new URL(`${location.origin}/match/${clip.matchId??match?.id??'match-001'}`);url.searchParams.set('start',String(Math.round(clip.start)));url.searchParams.set('end',String(Math.round(clip.end)));try{await navigator.clipboard.writeText(url.toString());setToast('Clip link copied.');}catch{setToast(url.toString());}};
  const saveClip=()=>{if(clipStart===null||clipEnd===null)return;setClips(prev=>[{id:crypto.randomUUID(),matchId:match?.id,title:title.trim(),notes,tags:tags.split(',').map(t=>t.trim()).filter(Boolean),start:clipStart,end:clipEnd,annotations},...prev]);setTitle('');setNotes('');setTags('');setAnnotations([]);setToast('Clip saved to your library');};
  const reviewSuggestion=(moment:typeof suggestions[number])=>{setTime(moment.start);clipStop.current=moment.end;setPlaying(true);};
  const createFromSuggestion=(moment:typeof suggestions[number])=>{setTime(moment.start);setPlaying(false);clipStop.current=null;setClipStart(moment.start);setClipEnd(moment.end);setTitle(moment.title);setNotes(moment.detail);setAnnotations([]);setToast('Suggested moment ready to clip');};
  const currentIndex=frames.findIndex(f=>f.timestamp>=time);const previous=frames.slice(Math.max(0,currentIndex-18),Math.max(0,currentIndex));
  if(!match) return <div className="welcome-shell"><header className="topbar welcome-topbar"><a className="brand" href="/"><span className="brand-mark"><SoccerBallLogo/></span><span>matchflow<span className="brand-period">.</span></span></a><span className="welcome-edition">US SOCCER × COLORSTACK TECH LEAGUE</span><div className="top-spacer"/><button className="settings-button" aria-label="Settings"><Settings2 size={17}/></button></header><main className="welcome-main">{loading&&<MatchLoadingOverlay/>}<span className="welcome-twinkle twinkle-one" aria-hidden="true">✦</span><span className="welcome-twinkle twinkle-two" aria-hidden="true">✧</span><div className="welcome-copy"><div className="welcome-kicker"><span/> MATCH ANALYSIS STUDIO <span/></div><h1>Every moment<br/>has a <em>pattern.</em></h1><p>Watch the movement behind the match. Find a moment, make it yours, and share the story with your team.</p><div className="team-credit"><span>BUILT BY</span><div><b>Yateeka Goyal</b><b>La'Niya Robinson</b><b>Madhuri Tumula</b><b>Amy Birkneh</b></div></div></div><section className="match-picker"><div className="picker-heading"><div><span className="eyebrow">YOUR FILM ROOM</span><h2>Select a match</h2></div><span className="picker-count">{matches.length} MATCHES</span></div><div className="match-cards">{matches.map((m,index)=><article className={`match-option ${selectedMatch===m.id?'chosen':''}`} key={m.id} onClick={()=>setSelectedMatch(m.id)}><button className="match-card-main" onClick={()=>setSelectedMatch(m.id)}><span className="match-number">{String(index+1).padStart(2,'0')}</span><span className="match-vs"><b>{m.name}</b><small>{m.competition}</small></span><span className="match-duration"><Clock3 size={12}/>{m.source==='skillcorner'?'90 min':formatTime(m.duration)}</span></button><div className="match-card-footer"><span>{m.date}</span><button className="match-load-card" disabled={loading} onClick={e=>{e.stopPropagation();void doLoad(m);}}>{loading&&selectedMatch===m.id?<><span className="spinner"/> Loading</>:<>Open match <ArrowRight size={13}/></>}</button></div></article>)}</div><div className="local-divider"><span/> OR BRING YOUR OWN TRACKING <span/></div><label className="local-drop"><UploadCloud size={17}/><span><b>Load local tracking data</b><small>Choose a SkillCorner .json or .jsonl file</small></span><ArrowRight size={15}/><input type="file" accept=".json,.jsonl,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void doFile(f);e.currentTarget.value='';}}/></label>{error&&<p className="welcome-error"><CircleHelp size={14}/>{error}</p>}</section><PixelCharacters celebration={false}/></main>{toast&&<div className="toast">{toast}</div>}</div>;
  return <div className="app-shell"><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><SoccerBallLogo/></span><span>matchflow<span className="brand-period">.</span></span><small>TRACKING STUDIO</small></a><div className="top-divider"/><div className="match-control"><span className="eyebrow">MATCH</span><MatchSelector matches={matches} value={selectedMatch} onChange={setSelectedMatch}/></div><MatchLoader loading={loading} onLoad={()=>void doLoad()} onFile={f=>void doFile(f)} error={error}/><div className="top-spacer"/><button className="settings-button" aria-label="Settings"><Settings2 size={17}/></button><button className="avatar">MF</button></header>
    <main className="main-content">{loading&&<MatchLoadingOverlay/>}<div className="page-heading"><div><div className="breadcrumb"><span>MATCH ANALYSIS</span></div><h1>{match.name} <span className="live-badge"><i/> {match.source==='local'?'LOCAL FILE':match.source==='skillcorner'?'SKILLCORNER':'DEMO'}</span></h1><p>{match.competition} <i/> {match.date}</p></div></div>
      <div className="workspace-grid"><section className="viewer-column"><div className="section-label"><span><span className="section-dot"/> MATCH MOVEMENT</span><span className="frame-label">LIVE MOMENT <b>{formatTime(time)}</b><i/> PERIOD <b>{currentFrame?.period??'—'}</b></span></div>{currentFrame?<SoccerField frame={currentFrame} selectedId={selectedPlayer} onSelect={id=>setSelectedPlayer(id)} trails={trails} labels={labels} speedLabels={speedLabels} ballTrail={ballTrail} shape={shape} previous={previous} homeName={match.homeTeamName??'Team A'} awayName={match.awayTeamName??'Team B'} drawMode={drawMode} canDraw={!playing} annotations={annotations} onAnnotation={mark=>setAnnotations(a=>[...a,{...mark,id:crypto.randomUUID()}])}/>:<div className="field-loading">Loading match movement…</div>}<PlaybackControls time={time} duration={duration} playing={playing} speed={speed} onPlay={()=>setPlaying(v=>!v)} onRestart={()=>{setTime(0);setPlaying(false);clipStop.current=null;}} onSkip={n=>setTime(v=>Math.max(0,Math.min(duration,v+n)))} onSpeed={setSpeed}/><Timeline time={time} duration={duration} start={clipStart} end={clipEnd} clips={clips} onChange={v=>{setTime(v);setPlaying(false);clipStop.current=null;}}/><div className="tools-row"><div className="tools-title"><SlidersHorizontal size={14}/><span>MORE</span></div><Toggle label="Speed" active={speedLabels} onClick={()=>setSpeedLabels(v=>!v)}/><Toggle label="Trails" active={trails} onClick={()=>setTrails(v=>!v)}/><Toggle label="Names" active={labels} onClick={()=>setLabels(v=>!v)}/><Toggle label="Ball trail" active={ballTrail} onClick={()=>setBallTrail(v=>!v)}/><Toggle label="Team shape" active={shape} onClick={()=>setShape(v=>!v)}/><PitchAnnotationTools mode={drawMode} setMode={setDrawMode} playing={playing} onClear={()=>setAnnotations([])} count={annotations.length}/></div><PlayerInfo player={activePlayer} onClose={()=>setSelectedPlayer(null)} homeName={match.homeTeamName??'Team A'} awayName={match.awayTeamName??'Team B'}/></section>
      <aside className="side-column"><ClipCreator time={time} start={clipStart} end={clipEnd} title={title} notes={notes} tags={tags} setTitle={setTitle} setNotes={setNotes} setTags={setTags} onStart={()=>{setClipStart(time);setAnnotations([]);if(clipEnd!==null&&clipEnd<=time)setClipEnd(null);}} onEnd={()=>setClipEnd(time)} onSave={saveClip}/><section className="panel match-info-panel"><div className="panel-heading"><div><span className="eyebrow">MATCH INFO</span><h3>At this moment</h3></div><span className="heading-icon"><MapPin size={16}/></span></div><div className="match-info-grid"><div><span>PLAYERS ON FIELD</span><b><UsersRound size={13}/> {currentFrame?.players.length??22}</b></div><div><span>BALL POSITION</span><b>{currentFrame?.ball.x.toFixed(1)??'—'}, {currentFrame?.ball.y.toFixed(1)??'—'} <small>m</small></b></div></div></section><SuggestedMoments moments={suggestions} onReview={reviewSuggestion} onCreate={createFromSuggestion}/><ClipLibrary clips={clips} onPlay={playClip} onShare={clip=>void shareClip(clip)} onDelete={id=>setClips(v=>v.filter(c=>c.id!==id))}/></aside></div>
    </main>{toast&&<div className="toast"><Command size={14}/>{toast}</div>}</div>;
}
function Toggle({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button className={`tool-toggle ${active?'active':''}`} onClick={onClick}><i/>{label}</button>;}

function SoccerBallLogo(){return <svg viewBox="0 0 32 32" width="19" height="19" aria-hidden="true"><circle cx="16" cy="16" r="12" fill="#fff7fa" stroke="#5a0016" strokeWidth="1.7"/><path d="m16 9 5 3.6-1.9 5.8h-6.2L11 12.6z" fill="#ea8eab" stroke="#5a0016" strokeWidth="1.3" strokeLinejoin="round"/><path d="m16 9-.2-5M11 12.6 6.2 11m6.7 7.8-3.2 4.9m9.4-4.9 3.2 4.9m-1.3-11.1 4.8-2" fill="none" stroke="#5a0016" strokeWidth="1.25" strokeLinecap="round"/></svg>;}
